services:
  mysql:
    image: mysql:8.0
    container_name: propertymanager-mysql
    environment:
      MYSQL_DATABASE: propertymanager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propertymanager-app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge