services:
  mysql:
    image: mysql:8.0
    container_name: propertymanager-mysql
    environment:
      MYSQL_DATABASE: propertymanager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propertymanager-app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge